apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- route.yaml
images:
- name: contact-service-image
  newName: ghcr.io/atra2396/prototyping-demo
  newTag: d7aa51ab93ccf431e284dabeb37cd449dc1d6fec
