apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: contact-service-pvc-argo-2
spec:
  resources:
    requests:
      storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany