apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
images:
- name: contact-service-image
  newName: $REGISTRY/$IMAGE_NAME
  newTag: 0f3cd067b679699234786fc013022e70065cf5c8
