apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
images:
- name: contact-service-image
  newName: ghcr.io/atra2396/prototyping-demo
  newTag: master
